# log config
logging.config=${JUXTAPOSE_HOME}/conf/logback.xml
logging.level=INFO

[ProxyServer]
proxy.proto=JUXTA
proxy.host=0.0.0.0
proxy.port=443
proxy.auth=true
proxy.tls=true
proxy.username=root
proxy.password=root

[Encrypt]
encrypt.method=pem
encrypt.server.port=2202